---

- name: Install the latest version packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: true
  loop:
    - "{{ PHP_FPM_PKGS_LIST }}"
  tags:
    - pkg

- name: Check if grub-pc is installed
  shell: dpkg -l | grep grub-pc || true
  register: grub_check
  changed_when: false
  failed_when: false

- name: Purge grub-pc if half-installed or broken
  apt:
    name: grub-pc
    state: absent
    purge: true
  become: true
  when: "'grub-pc' in grub_check.stdout"

- name: Prevent grub-pc from being reinstalled
  command: apt-mark hold grub-pc
  become: true
  when: "'grub-pc' in grub_check.stdout"

- name: Safe upgrade with rescue in case of grub-pc failure
  block:
    - name: Try to upgrade all packages
      apt:
        upgrade: dist
      become: true
      register: upgrade_result

  rescue:
    - name: Log that upgrade failed due to grub-pc
      debug:
        msg: "Upgrade failed — trying to remove grub-pc and retry"

    - name: Remove grub-pc to resolve upgrade block
      apt:
        name: grub-pc
        state: absent
        purge: true
      become: true
      ignore_errors: true

    - name: Fix dpkg after removing grub-pc
      shell: |
        DEBIAN_FRONTEND=noninteractive dpkg --configure -a
      become: true
      register: post_fix_result
      failed_when: false

    - name: Retry upgrade after removing grub-pc
      apt:
        name: "*"
        state: latest
      become: true
      tags:
        - pkg

- name: Clean apt package cache on VMs
  apt:
    autoclean: yes
  become: true

- name: Remove unused dependencies on VMs
  apt:
    autoremove: yes
    purge: yes
  become: true