---

- name: check if www dir exists {{ instance.name }}
  stat:
    path: /home/www-data/{{ instance.name }}/www
  register: www_file

- name: Create home directory for instance {{ instance.name }}
  file:
    path: /home/www-data/{{ instance.name }}/www
    state: directory
    owner: www-data
    group: root
    mode: '0755'

- name: Unarchive wordpress latest
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /home/www-data/{{ instance.name }}/www
    remote_src: yes
  when: not www_file.stat.exists

- name: change owner of wordpress instance {{ instance.name }}
  file: 
    dest: /home/www-data/{{ instance.name }}/www
    owner: www-data
    group: root
    recurse: yes
  when: not www_file.stat.exists

- name: Check if WordPress directory was extracted correctly for {{ instance.name }}
  stat:
    path: /home/www-data/{{ instance.name }}/www/wordpress
  register: wordpress_dir

- name: Assert WordPress directory exists for {{ instance.name }}
  assert:
    that:
      - wordpress_dir.stat.exists
    fail_msg: "❌ WordPress folder was not created for {{ instance.name }}"
    success_msg: "✅ WordPress folder present for {{ instance.name }}"

- name: check if config file exists {{ instance.name }}
  stat:
    path: /root/.my.cnf-{{ instance.db_user }}
  register: pass_file
  delegate_to: labfour.com

- name: Get wp pass
  shell: |
      cat /root/.my.cnf-{{ instance.db_user }}
  register: WORDPRESS_DB_PASSWORD
  delegate_to: labfour.com
  changed_when: false
  when: pass_file.stat.exists

- name: wordpress config file
  template:
    src: etc/wordpress/config.php.j2
    dest: /home/www-data/{{ instance.name }}/www/wordpress/wp-config.php
    owner: root
    group: root
    mode: '0644'
