---

- name: set sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value  }}"
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-sysctl.conf 
  with_items:
    - "{{ MARIADB_SYSCTL_LIST }}"

- name: Install the latest version packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: true
  loop:
    - "{{ MARIADB_PKGS_LIST }}"
  tags:
    - pkg

- name: Check if grub-pc is installed
  shell: dpkg -l | grep grub-pc || true
  register: grub_check
  changed_when: false
  failed_when: false

- name: Purge grub-pc if half-installed or broken
  apt:
    name: grub-pc
    state: absent
    purge: true
  become: true
  when: "'grub-pc' in grub_check.stdout"

- name: Prevent grub-pc from being reinstalled
  command: apt-mark hold grub-pc
  become: true
  when: "'grub-pc' in grub_check.stdout"

- name: Safe upgrade with rescue in case of grub-pc failure
  block:
    - name: Try to upgrade all packages
      apt:
        upgrade: dist
      become: true
      register: upgrade_result

  rescue:
    - name: Log that upgrade failed due to grub-pc
      debug:
        msg: "Upgrade failed — trying to remove grub-pc and retry"

    - name: Remove grub-pc to resolve upgrade block
      apt:
        name: grub-pc
        state: absent
        purge: true
      become: true
      ignore_errors: true

    - name: Fix dpkg after removing grub-pc
      shell: |
        DEBIAN_FRONTEND=noninteractive dpkg --configure -a
      become: true
      register: post_fix_result
      failed_when: false

    - name: Retry upgrade after removing grub-pc
      apt:
        name: "*"
        state: latest
      become: true
      tags:
        - pkg

- name: Clean apt package cache on VMs
  apt:
    autoclean: yes
  become: true

- name: Remove unused dependencies on VMs
  apt:
    autoremove: yes
    purge: yes
  become: true

- name: check if config file exist
  stat:
    path: /root/.my.cnf
  register: config_file

- name: Generate mysql root pass
  set_fact:
    MARIADB_ROOT_PASS: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=16') }}"
  when: not config_file.stat.exists

- name: Removes anonymous users
  mysql_user:
    name: ''
    host: "{{ item }}" 
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock
  with_items:
    - 127.0.0.1
    - localhost

- name: mysql .my.cnf {{ instance.name }}
  template:
    src: root/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
  when: not config_file.stat.exists

- name: Update MariaDB root password
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ MARIADB_ROOT_PASS }}"
  with_items:
    - 127.0.0.1
    - localhost
  when: not config_file.stat.exists

- name: mysql .my.cnf {{ user.name }}
  template:
    src: etc/mysql/mariadb.conf.d/50-server.cnf
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    owner: root
    group: root
    mode: '0600'
  notify:
    restart mariadb

- name: configuring instances
  include_tasks: database.yml
  loop: "{{ DB_INSTANCES }}"
  loop_control:
    loop_var: instance

- name: configuring users
  include_tasks: users.yml
  loop: "{{ DB_USERS }}"
  loop_control:
    loop_var: user
