---

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: true

- name: reload nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes
    daemon_reload: yes
  become: true